#controller_manager_ns: controller_manager

controller_list:
 - name: enabot_mover_r
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - enabot_joint_1_r
      - enabot_joint_2_r
      - enabot_joint_7_r
      - enabot_joint_3_r
      - enabot_joint_4_r
      - enabot_joint_5_r
      - enabot_joint_6_r

