controller_list:
  - name: fake_rarm_controller
    joints:
      - enabot_joint_1_r
      - enabot_joint_2_r
      - enabot_joint_7_r
      - enabot_joint_3_r
      - enabot_joint_4_r
      - enabot_joint_5_r
      - enabot_joint_6_r